// ========= Work Data =========
// Auto-generated by "npm run scan" - do not edit projects manually
const projects = [
  // AI短剧
  { title: '女角色 1', desc: 'AI 短剧角色设计', cat: 'ai-drama', type: 'image', img: '/portfolios/AI短剧/女1_merge.png' },
  { title: '女角色 2', desc: 'AI 短剧角色设计', cat: 'ai-drama', type: 'image', img: '/portfolios/AI短剧/女2_merge.png' },
  { title: '女角色 3', desc: 'AI 短剧角色设计', cat: 'ai-drama', type: 'image', img: '/portfolios/AI短剧/女3_merge.png' },
  { title: '故事板', desc: 'AI 短剧故事板设计', cat: 'ai-drama', type: 'image', img: '/portfolios/AI短剧/故事板.jpg' },
  { title: '男角色 1', desc: 'AI 短剧角色设计', cat: 'ai-drama', type: 'image', img: '/portfolios/AI短剧/男1_merge.png' },
  { title: '男角色 2', desc: 'AI 短剧角色设计', cat: 'ai-drama', type: 'image', img: '/portfolios/AI短剧/男2_merge.png' },
  { title: '男角色 3', desc: 'AI 短剧角色设计', cat: 'ai-drama', type: 'image', img: '/portfolios/AI短剧/男3_merge.png' },
  // AI视频作品集
  { title: '40s 微笑', desc: 'AI 视频短片', cat: 'ai-video', type: 'video', img: '/portfolios/AI视频作品集/40s微笑.mp4', video: '/portfolios/AI视频作品集/40s微笑.mp4' },
  { title: '意外的重逢', desc: 'AI 视频作品', cat: 'ai-video', type: 'video', img: '/portfolios/AI视频作品集/意外的重逢_poster.jpg', video: '/portfolios/AI视频作品集/意外的重逢.mp4' },
  { title: '比心舞', desc: 'AI视频作品', cat: 'ai-video', type: 'video', img: '/portfolios/AI视频作品集/比心舞.mp4', video: '/portfolios/AI视频作品集/比心舞.mp4' },
  // 电商
  { title: '商品主图一键生成', desc: 'AI 电商商品主图设计', cat: 'ecommerce', type: 'image', img: '/portfolios/电商/商品主图一键生成.png' },
  { title: '电商详情页', desc: '电商产品详情页设计', cat: 'ecommerce', type: 'image', img: '/portfolios/电商/电商详情页.png' },
  // 生活
  { title: '人物剪影', desc: '生活摄影 - 人物剪影', cat: 'life', type: 'image', img: '/portfolios/生活/人物剪影.jpg' },
  { title: '朋友圈照片', desc: '生活摄影记录', cat: 'life', type: 'image', img: '/portfolios/生活/朋友圈照片.png' },
]

const filterCategories = [
  { key: 'all', label: '全部' },
  { key: 'ai-drama', label: 'AI短剧' },
  { key: 'ai-video', label: 'AI视频' },
  { key: 'ecommerce', label: '电商' },
  { key: 'life', label: '生活' },
]

export { projects, filterCategories }
