// ========= Work Data =========
// Auto-generated by "npm run scan" - do not edit projects manually
const projects = [
  { title: '爱像是一场小雨', desc: 'AI 情感短片 · 雨天咖啡馆', cat: 'ai-video', type: 'video', img: '/portfolios/AI视频作品集/爱像是一场小雨_poster.jpg', video: '/portfolios/AI视频作品集/爱像是一场小雨.mp4', thumb: '/portfolios/.thumbnails/爱像是一场小雨.webp', date: '2026-09-28' },
  { title: '镜头配方与动态样片', desc: '动效节奏与界面演示剪辑', cat: 'video-edit', type: 'video', img: '/portfolios/剪辑作品/镜头配方与动态样片_poster.jpg', video: '/portfolios/剪辑作品/镜头配方与动态样片.mp4', thumb: '/portfolios/.thumbnails/镜头配方与动态样片.webp', date: '2026-09-28' },
  { title: '仙侠 · 秋千', desc: 'AI 古风角色动态化 · 竖屏', cat: 'ai-video', type: 'video', img: '/portfolios/AI视频作品集/仙侠秋千_poster.jpg', video: '/portfolios/AI视频作品集/仙侠秋千.mp4', thumb: '/portfolios/.thumbnails/仙侠秋千.webp', date: '2026-09-22' },
  { title: '世界 · 自然宣传片', desc: 'AI 风光镜头剪辑 + 原创配乐', cat: 'ai-video', type: 'video', img: '/portfolios/AI视频作品集/世界宣传片_poster.jpg', video: '/portfolios/AI视频作品集/世界宣传片.mp4', thumb: '/portfolios/.thumbnails/世界宣传片.webp', date: '2026-09-21' },
  { title: '心动频段', desc: 'AI 歌词短片 · 火车与芒草的黄昏', cat: 'ai-video', type: 'video', img: '/portfolios/AI视频作品集/心动频段_poster.jpg', video: '/portfolios/AI视频作品集/心动频段.mp4', thumb: '/portfolios/.thumbnails/心动频段.webp', date: '2026-09-21' },
  { title: '比心舞', desc: 'AI视频作品', cat: 'ai-video', type: 'video', img: '/portfolios/AI视频作品集/比心舞_poster.jpg', video: '/portfolios/AI视频作品集/比心舞.mp4', thumb: '/portfolios/.thumbnails/比心舞.webp', date: '2026-08-11' },
  { title: '商品主图一键生成', desc: 'AI 电商商品主图设计', cat: 'ecommerce', type: 'image', img: '/portfolios/电商/商品主图一键生成.png', thumb: '/portfolios/.thumbnails/商品主图一键生成.webp', date: '2026-08-10' },
  { title: '电商详情页', desc: '电商产品详情页设计', cat: 'ecommerce', type: 'image', img: '/portfolios/电商/电商详情页.png', thumb: '/portfolios/.thumbnails/电商详情页.webp', date: '2026-08-10' },
  { title: '人物剪影', desc: '生活摄影 - 人物剪影', cat: 'life', type: 'image', img: '/portfolios/生活/人物剪影.jpg', thumb: '/portfolios/.thumbnails/人物剪影.webp', date: '2026-08-05' },
  { title: '朋友圈照片', desc: '生活摄影记录', cat: 'life', type: 'image', img: '/portfolios/生活/朋友圈照片.png', thumb: '/portfolios/.thumbnails/朋友圈照片.webp', date: '2026-08-05' },
  { title: '女角色 1', desc: 'AI 短剧角色设计', cat: 'ai-drama', type: 'image', img: '/portfolios/AI短剧/女1_merge.png', thumb: '/portfolios/.thumbnails/女1_merge.webp', date: '2026-08-01' },
  { title: '女角色 2', desc: 'AI 短剧角色设计', cat: 'ai-drama', type: 'image', img: '/portfolios/AI短剧/女2_merge.png', thumb: '/portfolios/.thumbnails/女2_merge.webp', date: '2026-08-01' },
  { title: '女角色 3', desc: 'AI 短剧角色设计', cat: 'ai-drama', type: 'image', img: '/portfolios/AI短剧/女3_merge.png', thumb: '/portfolios/.thumbnails/女3_merge.webp', date: '2026-08-01' },
  { title: '故事板', desc: 'AI 短剧故事板设计', cat: 'ai-drama', type: 'image', img: '/portfolios/AI短剧/故事板.jpg', thumb: '/portfolios/.thumbnails/故事板.webp', date: '2026-08-01' },
  { title: '男角色 1', desc: 'AI 短剧角色设计', cat: 'ai-drama', type: 'image', img: '/portfolios/AI短剧/男1_merge.png', thumb: '/portfolios/.thumbnails/男1_merge.webp', date: '2026-08-01' },
  { title: '男角色 2', desc: 'AI 短剧角色设计', cat: 'ai-drama', type: 'image', img: '/portfolios/AI短剧/男2_merge.png', thumb: '/portfolios/.thumbnails/男2_merge.webp', date: '2026-08-01' },
  { title: '男角色 3', desc: 'AI 短剧角色设计', cat: 'ai-drama', type: 'image', img: '/portfolios/AI短剧/男3_merge.png', thumb: '/portfolios/.thumbnails/男3_merge.webp', date: '2026-08-01' },
  { title: '意外的重逢', desc: 'AI 视频作品', cat: 'ai-video', type: 'video', img: '/portfolios/AI视频作品集/意外的重逢_poster.jpg', video: '/portfolios/AI视频作品集/意外的重逢.mp4', thumb: '/portfolios/.thumbnails/意外的重逢.webp', date: '2026-06-22' },
  { title: '40s 微笑', desc: 'AI 视频短片', cat: 'ai-video', type: 'video', img: '/portfolios/AI视频作品集/40s微笑_poster.jpg', video: '/portfolios/AI视频作品集/40s微笑.mp4', thumb: '/portfolios/.thumbnails/40s微笑.webp', date: '2026-06-12' },
]

const filterCategories = [
  { key: 'all', label: '全部' },
  { key: 'ai-drama', label: 'AI短剧' },
  { key: 'ai-video', label: 'AI视频' },
  { key: 'ecommerce', label: '电商' },
  { key: 'life', label: '生活' },
  { key: 'video-edit', label: '剪辑' },
]

export { projects, filterCategories }
